<a href="https://colab.research.google.com/github/MirzaUmar1/SIC-Artificial-Intelligence/blob/main/Classwork/SICClass05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Class Tasks:**

## **Matrices**

**Determinent and Inverse of a matrix**

In [3]:
import numpy as np

A = np.array([[1,3],[5,7]])
B = np.array([[4,-6],[-8,12]])

detA = np.linalg.det(A)
Ainv = np.linalg.inv(A)
detB = np.linalg.det(B)

print("Determinent of A = ",detA)
print("Inverse of A = ",Ainv)
print("Determinent of B = ",detB)

Determinent of A =  -7.999999999999998
Inverse of A =  [[-0.875  0.375]
 [ 0.625 -0.125]]
Determinent of B =  0.0


In [8]:
A = np.array([[3,2],[4,7]])

detA = np.linalg.det(A)
Ainv = np.linalg.inv(A)

print("Determinent of A = ",detA)
print("Inverse of A = ",Ainv)

Determinent of A =  13.0
Inverse of A =  [[ 0.53846154 -0.15384615]
 [-0.30769231  0.23076923]]


**Matrix Addition, Subtraction and Multiplication**

In [7]:
A = np.array([[3,4],[5,6],[7,8]])
B = np.array([[1,9],[2,0]])

C = np.matmul(A,B)

print(C)

[[11 27]
 [17 45]
 [23 63]]


**Transpose of a matrix**

In [15]:
A = np.array([[0,1,2],[1,7,8],[2,8,9]])
print("Matrix = ",A)

A_trp = A.T
print("Transpose of Matrix = ",A_trp)

if (A == A_trp).all():
  print("Matrix is symmetric")
else:
  print("Matrix is non symmetric")

Matrix =  [[0 1 2]
 [1 7 8]
 [2 8 9]]
Transpose of Matrix =  [[0 1 2]
 [1 7 8]
 [2 8 9]]
Matrix is symmetric


In [17]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix = ",A)

A_trp = A.T
print("Transpose of Matrix = ",A_trp)

if (A == A_trp).all():
  print("Matrix is symmetric")
else:
    print("Matrix is non symmetric")

Matrix =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of Matrix =  [[1 4 7]
 [2 5 8]
 [3 6 9]]
Matrix is non symmetric


**Matrix Manipulation**

Solve following system of equations:

50 = 10 + 15w1 + 20w2 + 3w3 + 12w4 + 5w3<br>
35 = 10 + 12w1 + 25w2 + 2w3 + 10w4 + 8w5<br>
65 = 10 + 18w1 + 35w2 + 4w3 + 16w4 + 12w5<br>
25 = 10 + 8w1 + 5w2 + 1w3 + 5w4 + 2w5<br>
55 = 10 + 16w1 + 4w2 + 3w3 + 14w4 + 4w5<br>
25 = 10 + 12w1 + 3w2 + 2w3 + 8w4 + 5w5





In [20]:
x = np.array([[1,15,30,3,12,5],[1,12,25,2,10,8],[1,18,35,4,16,12],[1,8,5,1,5,2],[1,16,4,3,14,4],[1,12,3,2,8,5]])

x_inv = np.linalg.inv(x)
Y = np.array([[50],[35],[65],[25],[55],[25]])

W = np.matmul(x_inv,Y)

print(W)

[[ 6.29596977e+01]
 [-1.37657431e+01]
 [-5.03778338e-02]
 [ 3.59193955e+01]
 [ 7.93450882e+00]
 [-1.58690176e+00]]


**Eigen Values and Eigen Vectors**

In [21]:
A = np.array([[3,6],[8,4]])

lambdas, vectors = np.linalg.eig(A)

print("Eigen Values = ",lambdas)
print("Eigen Vectors = ",vectors)

Eigen Values =  [-3.44622199 10.44622199]
Eigen Vectors =  [[-0.68131786 -0.62743446]
 [ 0.73198769 -0.77866938]]


## **Derivatives**

**Derivative of a constant function.**

In [32]:
import sympy as sp

# (a) f(x) = x**2020 + 3*x**3 - 1

x = sp.Symbol('x')
fx = x**2020+3*x*x*x-1

dfx = sp.diff(fx,x)
print(dfx)

2020*x**2019 + 9*x**2


In [30]:
# g(x) = x/(x+1)

x = sp.symbols('x')
gx = x/(x+1)

dfx = sp.simplify(sp.diff(gx,x))
print(dfx)

(x + 1)**(-2)
