<a href="https://colab.research.google.com/github/MirzaUmar1/SIC-Artificial-Intelligence/blob/main/Assignments/SICAssignment01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Task 2: Data type manipulations**

Write a function nested_list_flatten that takes a list containing both integers and lists of
integers (nested at arbitrary depths) and flattens it into a single list.
You cannot use any built-in Python flattening functions or methods.
You must implement this recursively.
Ensure your solution handles deeply nested lists efficiently.

In [8]:
def nested_list_flatten(nested_list):
    # Define an empty list to hold the flattened elements
    flat_list = []

    # Iterate through each element in the nested_list
    for element in nested_list:
        # If the element is a list, recursively call nested_list_flatten
        if isinstance(element, list):
            flat_list.extend(nested_list_flatten(element))
        else:
            # If it's not a list, add the element directly to flat_list
            flat_list.append(element)

    return flat_list

# Test Cases
# Test with a simple nested list
print(nested_list_flatten([1, [2, 3], [4, [5, 6]], 7]))

# Test with deeper nesting
print(nested_list_flatten([1, [2, [3, [4, [5]]]], 6]))

# Test with an empty list
print(nested_list_flatten([]))

# Test with a list containing empty lists
print(nested_list_flatten([[], [1, 2], [[], 3]]))


[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6]
[]
[1, 2, 3]


**Task 3: String Manipulation**

Create a function custom_split that mimics Python’s str.split() but without using any string
methods like split(), replace(), or join(). The function should split a string by spaces and return a
list of words. You can assume words are separated by a single space.

In [3]:
def custom_split(input_string):
    # List to store the split words
    words = []

    # Temporary variable to store the current word
    current_word = ""

    # Iterate over each character in the string
    for char in input_string:
        if char == ' ':
            # If a space is found and we have a current word, add it to the list
            if current_word:
                words.append(current_word)
                current_word = ""  # Reset current_word for the next word
        else:
            # Add the character to the current word
            current_word += char

    # Add the last word if any (as there may not be a space after the last word)
    if current_word:
        words.append(current_word)

    return words

# Test Cases
# Basic test case
print(custom_split("This is a test"))

# Test case with leading and trailing spaces
print(custom_split("   Hello world   "))

# Test case with multiple spaces between words
print(custom_split("Python   is   fun"))

# Test case with an empty string
print(custom_split(""))

# Test case with a single space
print(custom_split(" "))


['This', 'is', 'a', 'test']
['Hello', 'world']
['Python', 'is', 'fun']
[]
[]


**Task 4: Numpy Array Construction**

Write a function manual_identity_matrix that creates an identity matrix of size n x n without
using NumPy’s built-in np.eye() or np.identity() functions.

In [7]:
def manual_identity_matrix(n):
    # Create a 2D list with all zeros
    identity = [[0 for _ in range(n)] for _ in range(n)]

    # Set the diagonal elements to 1
    for i in range(n):
        identity[i][i] = 1

    return identity

# Test Cases
# 3x3 identity matrix
print(manual_identity_matrix(3))

# 5x5 identity matrix
print(manual_identity_matrix(5))

# 1x1 identity matrix
print(manual_identity_matrix(1))



[[1, 0, 0], [0, 1, 0], [0, 0, 1]]
[[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]]
[[1]]


T**ask 5: Custom Dot Product Manipulation**

Implement your own function custom_dot_product to compute the dot product of two vectors
without using np.dot (). Instead, perform the element-wise multiplication and summation
manually using loops or list comprehensions.

In [9]:
def custom_dot_product(vector1, vector2):
    # Check if the lengths of the vectors match
    if len(vector1) != len(vector2):
        raise ValueError("Vectors must be of the same length")

    # Calculate the dot product
    dot_product = 0
    for i in range(len(vector1)):
        dot_product += vector1[i] * vector2[i]

    return dot_product

# Test Cases
# Basic dot product example
print(custom_dot_product([1, 2, 3], [4, 5, 6]))

# Test with negative numbers
print(custom_dot_product([-1, 2, -3], [4, -5, 6]))

# Test with zeros
print(custom_dot_product([0, 0, 0], [1, 2, 3]))


32
-32
0


**Task 6: Broadcasting with NumPy**

You have two 1D NumPy arrays:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30, 40])
Using broadcasting, generate a 2D array where each element of arr1 is multiplied by all
elements of arr2. Your output should look like this:

output
[[ 10 20 30 40]
[ 20 40 60 80]
[ 30 60 90 120]]
Do not use loops.

In [6]:
import numpy as np

# Define the arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30, 40])

# Reshape arr1 to (3, 1) so that it can broadcast properly with arr2
arr1_reshaped = arr1.reshape(3, 1)

# Use broadcasting to multiply arr1 with arr2
result = arr1_reshaped * arr2

# Print the resulting 2D array
print(result)


[[ 10  20  30  40]
 [ 20  40  60  80]
 [ 30  60  90 120]]
