<a href="https://colab.research.google.com/github/MirzaUmar1/SIC-Artificial-Intelligence/blob/main/Lab%20Tasks/SICLab03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Task 1:**

Given the following 2D NumPy array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
Transpose the array and print the result.

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

print("Array: ", arr)

arr_tr = np.transpose(arr)
print("Transpose: ", arr_tr)


Array:  [[1 2 3]
 [4 5 6]]
Transpose:  [[1 4]
 [2 5]
 [3 6]]


**Task 2:**

Accessing Elements in a 2D NumPy Array
Given the following 2D NumPy array:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Use indexing to:

Access the element at row 1, column 2 and print its value.
Access the entire second row and print its values.
Access the entire first column and print its values.

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Array: ", arr)

print("Element at row 1, column 2: ", arr[0,1])

print("Entire second row: ", arr[1,:])

print("Entire first column: ", arr[:,0])

Array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2:  2
Entire second row:  [4 5 6]
Entire first column:  [1 4 7]


**Task 3:**

Given the following 1D NumPy array:

x = np.array([1, 2, 3, 4, 5])

Compute the Euclidean norm (L2 norm) of the array and print its value.


In [ ]:
import numpy as np

x= np.array([1,2,3,4,5])

print("Array: ", x)

norm = np.linalg.norm(x)

print("Euclidean norm: ", norm)

Array:  [1 2 3 4 5]
Euclidean norm:  7.416198487095663
